#!/bin/bash

#    This file is part of rpi2cosm.
#    Copyright (c) 2012, Ricardo Cabral <ricardo.arturo.cabral@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

realpath=`realpath $0`

echo "========================================"
echo "=    rpi2cosm configuration utility    ="
echo "========================================"
while [[ -z "$api_key" ]]; do
echo -n "Enter your API Key: "
read api_key
done

while [[ -z "$feed" ]]; do
echo -n "Enter this device's Feed ID: "
read feed
done

iface_possible=`ip link show | grep ^[0-9] | cut -d ' ' -f 2 | cut -d ':' -f 1 | tr "\n" ', ' | sed "s/,$//"`
echo -n "Enter your default network interface (${iface_possible}) (default: eth0): "
read iface
if [[ -z "$iface" ]]; then
iface="eth0"
fi

if [[ -f "~/.rpi2cosm.conf" ]]; then
while true; do
  echo -n "Configuration file already exists. Would you like to make a back up first? (y/n)"
  read option
  if [[ "$option" = "n" ]]; then
    break
  elif [[ "$option" = "y" ]]; then
    echo "Moved old configuration to ${output_file}.backup"
    cp ${output_file} ${output_file}.backup
    break
  fi
done
fi

echo "#    Generated by rpi2cosm configuration utility ($realpath)        " > /tmp/rpi2cosm.conf
echo "#    on `date`                                                      " >> /tmp/rpi2cosm.conf
echo "#    Feel free to modify this file or use the configuration utility." >> /tmp/rpi2cosm.conf
echo "                                                                    " >> /tmp/rpi2cosm.conf
echo "api_key=${api_key}                                                  " >> /tmp/rpi2cosm.conf
echo "feed=$feed                                                          " >> /tmp/rpi2cosm.conf
echo "iface=$iface                                                        " >> /tmp/rpi2cosm.conf
rm ~/.rpi2cosm.conf
mv /tmp/rpi2cosm.conf ~/.rpi2cosm.conf
if [[ $? = 0 ]]; then
  echo "Configuration file saved to ~/.rpi2cosm.conf"
else
  echo "Unable to save configuration file"
fi

echo "Updating crontab..."
# Get crontab without any entries to rpi2cosm and save to temporary file
crontab -l | grep -v rpi2cosm > /tmp/crontab
# Get the directory where setup utility is; assuming rpi2cosm.sh is there too
dirname=`dirname $realpath`
# Add a new entry to our crontab
echo "*/5 * * * * ${dirname}/rpi2cosm.sh" >> /tmp/crontab
# Replace current crontab with our version
crontab /tmp/crontab
# Show it to the user
#env EDITOR=nano crontab -e
crontab -l

# Exit
exit 0
